[central_hub]
central-hub-cp ansible_host=192.168.1.107
central-hub-worker ansible_host=192.168.1.102

[prod_cluster]
prod-cluster-cp ansible_host=192.168.1.103
prod-cluster-worker ansible_host=192.168.1.104

[dev_cluster]
dev-cluster-cp ansible_host=192.168.1.105
dev-cluster-worker ansible_host=192.168.1.106

[control_planes]
central-hub-cp
prod-cluster-cp
dev-cluster-cp

[workers]
central-hub-worker
prod-cluster-worker
dev-cluster-worker

[all:vars]
ansible_user=k8sadmin
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3